# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: release

# Trigger the workflow when:
on:
  # A push occurs to one of the matched branches.
  push:
    branches: [master]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    # NOTE: This name appears in GitHub's Checks API.
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build app
        run: yarn build
      # https://github.com/actions/upload-pages-artifact#example-permissions-fix-for-linux
      - name: Apply read permissions to build files
        run: |
          chmod -c -R +rX "dist/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload build artifacts from the dist/ directory.
          path: 'dist/'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
